import { StyleSheet } from "react-native";
import { Colors } from "../GlobalStyles/colors";
import { globalStyles } from "../GlobalStyles/globalStyles";

export const lessonDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundPrimary,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: Colors.backgroundPrimary,
  },
  errorText: {
    ...globalStyles.bodyText,
    color: Colors.error,
    textAlign: "center",
    marginBottom: 20,
  },
  retryButton: {
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 8,
    backgroundColor: Colors.primary,
    marginTop: 10,
  },
  retryButtonText: {
    ...globalStyles.buttonText,
    color: Colors.white,
  },
  noQuestionText: {
    ...globalStyles.bodyText,
    textAlign: "center",
    color: Colors.textSecondary,
    marginBottom: 20,
  },

  introContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: Colors.backgroundPrimary,
  },
  lessonTitle: {
    ...globalStyles.headerText,
    marginBottom: 15,
    textAlign: "center",
    color: Colors.textPrimary,
  },
  lessonDescription: {
    ...globalStyles.bodyText,
    textAlign: "center",
    marginBottom: 25,
    color: Colors.textSecondary,
  },
  lessonInfo: {
    ...globalStyles.bodyText,
    color: Colors.textPrimary,
    marginBottom: 10,
    fontWeight: "bold",
  },
  startButton: {
    width: "80%",
    paddingVertical: 15,
    borderRadius: 10,
    backgroundColor: Colors.accentPrimary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
  },
  startButtonText: {
    ...globalStyles.buttonText,
    color: Colors.white,
  },
  backButton: {
    width: "80%",
    paddingVertical: 15,
    borderRadius: 10,
    borderColor: Colors.lightGray,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    backgroundColor: Colors.backgroundSecondary,
  },
  backButtonText: {
    ...globalStyles.buttonText,
    color: Colors.textPrimary,
  },

  exerciseScreenContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: Colors.backgroundPrimary,
  },
  scoreAndProgressText: {
    ...globalStyles.bodyText,
    textAlign: "center",
    marginBottom: 15,
    color: Colors.textSecondary,
  },
  exerciseContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 10,
    paddingHorizontal: 15,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 20,
  },
  questionText: {
    ...globalStyles.titleText,
    marginBottom: 25,
    textAlign: "center",
    color: Colors.textPrimary,
    lineHeight: 30,
  },
  optionsContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 20,
  },
  optionButton: {
    width: "90%",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.lightGray,
    backgroundColor: Colors.backgroundSecondary,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  optionText: {
    ...globalStyles.bodyText,
    color: Colors.textPrimary,
    fontWeight: "500",
  },
  selectedOption: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + "1A",
    borderWidth: 2,
  },
  correctOption: {
    backgroundColor: Colors.success + "33",
    borderColor: Colors.success,
    borderWidth: 2,
  },
  wrongOption: {
    backgroundColor: Colors.error + "33",
    borderColor: Colors.error,
    borderWidth: 2,
  },
  textInput: {
    width: "90%",
    height: 50,
    borderColor: Colors.lightGray,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 20,
    backgroundColor: Colors.backgroundSecondary,
    ...globalStyles.bodyText,
    color: Colors.textPrimary,
  },
  submitButton: {
    width: "90%",
    paddingVertical: 15,
    borderRadius: 10,
    backgroundColor: Colors.accentPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  submitButtonText: {
    ...globalStyles.buttonText,
    color: Colors.white,
  },

  summaryContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: Colors.backgroundPrimary,
  },
  summaryTitle: {
    ...globalStyles.headerText,
    marginBottom: 15,
    color: Colors.textPrimary,
  },
  motivationText: {
    ...globalStyles.bodyText,
    textAlign: "center",
    marginBottom: 30,
    color: Colors.textSecondary,
    fontStyle: "italic",
  },
  summaryStats: {
    width: "80%",
    marginBottom: 30,
    alignItems: "center",
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 10,
    padding: 20,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  summaryStatText: {
    ...globalStyles.bodyText,
    marginBottom: 10,
    color: Colors.textPrimary,
  },
  summaryStatCorrect: {
    color: Colors.success,
    fontWeight: "bold",
  },
  summaryStatIncorrect: {
    color: Colors.error,
    fontWeight: "bold",
  },
  summaryPointsText: {
    ...globalStyles.titleText,
    marginTop: 10,
    color: Colors.accentPrimary,
    fontWeight: "bold",
  },
  backToPathButton: {
    width: "80%",
    paddingVertical: 15,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  backToPathButtonText: {
    ...globalStyles.buttonText,
    color: Colors.white,
  },
});
